In [49]:
import pandas as pd

df = pd.read_csv("house-price.csv")
# df[df['Address'].isnull()]
df = df.dropna(subset=['Address'])
print(df.isnull().sum())   # باید Address حالا 0 نشون بده
print(len(df))             # تعداد ردیف‌های باقی‌مونده

Area          0
Room          0
Parking       0
Warehouse     0
Elevator      0
Address       0
Price         0
Price(USD)    0
dtype: int64
3456

In [50]:
df['Area'] = pd.to_numeric(df['Area'], errors='coerce')

In [51]:
df[df['Area'] > 196.5]

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
59,215.0,3,True,True,True,Pakdasht,1.750000e+09,58333.33
84,300.0,3,True,True,False,Baghestan,1.500000e+09,50000.00
160,245.0,3,True,True,True,Farmanieh,2.695000e+10,898333.33
167,200.0,3,True,True,True,Pasdaran,1.200000e+10,400000.00
174,236.0,4,True,True,True,Gheitarieh,2.000000e+10,666666.67
...,...,...,...,...,...,...,...,...
3264,205.0,3,True,True,True,Farmanieh,2.000000e+10,666666.67
3267,220.0,4,True,True,False,Azarbaijan,1.500000e+10,500000.00
3334,285.0,4,True,True,True,Shahrake Gharb,2.850000e+10,950000.00
3366,197.0,3,True,True,True,Marzdaran,1.556300e+10,518766.67
3388,200.0,2,False,False,False,Rudhen,2.850000e+09,95000.00

In [52]:
before = len(df)
df = df[df['Area'] <= 196.5]
after = len(df)

print(f"Count before removing: {before}")
print(f"Count after removing: {after}")
print(f"Removed: {before - after} Rowes ({(before-after)/before*100:.2f}%)")

Count before removing: 3456
Count after removing: 3212
Removed: 244 Rowes (7.06%)

In [53]:
outlier_indices = df[df['Area'] > 196.5].index
df = df.drop(outlier_indices)

In [57]:
df = df[df['Area'] <= 196.5]
after = len(df)
df

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
0,63.0,1,True,True,True,Shahran,1.850000e+09,61666.67
1,60.0,1,True,True,True,Shahran,1.850000e+09,61666.67
2,79.0,2,True,True,True,Pardis,5.500000e+08,18333.33
3,95.0,2,True,True,True,Shahrake Qods,9.025000e+08,30083.33
4,123.0,2,True,True,True,Shahrake Gharb,7.000000e+09,233333.33
...,...,...,...,...,...,...,...,...
3474,86.0,2,True,True,True,Southern Janatabad,3.500000e+09,116666.67
3475,83.0,2,True,True,True,Niavaran,6.800000e+09,226666.67
3476,75.0,2,False,False,False,Parand,3.650000e+08,12166.67
3477,105.0,2,True,True,True,Dorous,5.600000e+09,186666.67
3478,82.0,2,False,True,True,Parand,3.600000e+08,12000.00